import { Products } from './Products';

export const PRODUCTS: Products[] = [
    {
        id: 1,
        name: "escoba",
        description: "grande",
        price: "200$",
        expDate: new Date(45),
        image: "no hay",
        score: 12,
    },
    {
        id: 2,
        name: "cuchara",
        description: "grande",
        price: "200$",
        expDate: new Date(30),
        image: "no hay",
        score: 5,  
    }
    
]

